# SPDX-FileCopyrightText: 2022 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

[target.aarch64-linux-android]
linker = "aarch64-linux-android30-clang"

[target.x86_64-linux-android]
linker = "x86_64-linux-android30-clang"