# SPDX-FileCopyrightText: 2022 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

projects:
  - name: Envoy + PP Clean Start
    id: 61d85527a3996201477cbeec
  - name: Envoy
    id: 62f8fb448baeedf0e9577bc2

format: flat
components: true
