# SPDX-FileCopyrightText: 2022 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "tor-ffi"
version = "0.1.0"
authors = ["Igor Cota <igor@foundationdevices.com>"]
edition = "2018"

[lib]
name = "tor_ffi"
crate-type = ["cdylib", "staticlib"]

[dependencies]
libtor-sys = { git = "https://github.com/icota/libtor-sys", rev = "849a559dbdac17d04eb8ebe43db96c78e4bb9fd1", features = ["vendored-openssl"] }

[build-dependencies]
cbindgen = "0.24.3"
